[settings]
# Name of a language file without extension, english.toml by default
language = "english"

# Enable logging of all CustomPayload packets for debugging purposes
debug = false

# If the same payload is sent twice, only the first triggers a check
skip_duplicates = false
