main: org.hackedserver.spigot.HackedServerPlugin
name: HackedServer
version: ${projectVersion}
author: Th0rgal
softdepend: [ ViaVersion, ProtocolSupport ]
depend: [ ProtocolLib ]
api-version: 1.17
commands:
  hackedserver:
    description: Main command of HackedServer.
    aliases: [ hs, hackeds, hserver ]